### ISSUE TITLE
Game crash when using a broken silent tool

### ISSUE THREAD

**Issue by breon** [DarkPacks/Escape-From-2020#5]
I had the game crash a few times tonight and wasn't sure why. Then I saw the pattern. The first time was when i was fighting a skeleton and my silent axe broke. Then, when I was trying to dig down to get stone to repair it, the game crashed again because of my broken shovel. This was pretty repeatable.

### Preconditions
* Broken shovel or axe

### Steps
* Attempt to mine with shovel
* Attempt to attack with axe

### Expected
* Mining/attacking doesn't work

### Actual
* Game crashes

### Notes
* See attached logs

[crash-2020-11-12_21.16.54-client.txt](https://github.com/DarkPacks/Escape-From-2020/files/5535239/crash-2020-11-12_21.16.54-client.txt)
[crash-2020-11-12_21.27.59-client.txt](https://github.com/DarkPacks/Escape-From-2020/files/5535240/crash-2020-11-12_21.27.59-client.txt)
[crash-2020-11-12_21.31.02-client.txt](https://github.com/DarkPacks/Escape-From-2020/files/5535241/crash-2020-11-12_21.31.02-client.txt)
[crash-2020-11-13_00.52.34-client.txt](https://github.com/DarkPacks/Escape-From-2020/files/5535242/crash-2020-11-13_00.52.34-client.txt)

**Comment by justinrusso** [comment]
Fixed in cfda5c6cbe1e4902363fbd036c5b69399a605611
