### ISSUE TITLE
Increasing Redstone Ore Veins

### ISSUE THREAD

**Issue by Digimasterhir0** [DarkPacks/Escape-From-2020#6]
Hi! I spent about 2 hours to find Redstone in my survival world and did not find it at all. After that, in my creative world, I cleared some chunks using World Stripper and found that it was extremely rare. What is more, this veins were too small. And it not enough for starting playing Thermal or Powah. 

Maybe it might be better to increase their sizes or its amount in one chunk.

Have a good day. DigimasterHiro.

**Comment by Hank-Riker** [comment]
I agree. I’ve spent many hours in survival without finding any redstone at all.

**Comment by justinrusso** [comment]
Fixed in cfda5c6cbe1e4902363fbd036c5b69399a605611
